export const STOCKS = {
    USA: [
        { ticker: "AAPL", name: "Apple Inc." },
        { ticker: "MSFT", name: "Microsoft" },
        { ticker: "AMZN", name: "Amazon" },
        { ticker: "NVDA", name: "NVIDIA" },
        { ticker: "GOOGL", name: "Alphabet (A)" },
        { ticker: "META", name: "Meta Platforms" },
        { ticker: "TSLA", name: "Tesla" },
        { ticker: "BRK-B", name: "Berkshire Hathaway" },
        { ticker: "UNH", name: "UnitedHealth" },
        { ticker: "LLY", name: "Eli Lilly" },
        { ticker: "JPM", name: "JPMorgan Chase" },
        { ticker: "XOM", name: "Exxon Mobil" },
        { ticker: "V", name: "Visa" },
        { ticker: "JNJ", name: "Johnson & Johnson" },
        { ticker: "MA", name: "Mastercard" },
        { ticker: "PG", name: "Procter & Gamble" },
        { ticker: "AVGO", name: "Broadcom" },
        { ticker: "HD", name: "Home Depot" },
        { ticker: "CVX", name: "Chevron" },
        { ticker: "MRK", name: "Merck & Co." },
        { ticker: "ABBV", name: "AbbVie" },
        { ticker: "COST", name: "Costco" },
        { ticker: "PEP", name: "PepsiCo" },
        { ticker: "ADBE", name: "Adobe" },
        { ticker: "KO", name: "Coca-Cola" },
        { ticker: "WMT", name: "Walmart" },
        { ticker: "BAC", name: "Bank of America" },
        { ticker: "CRM", name: "Salesforce" },
        { ticker: "TMO", name: "Thermo Fisher" },
        { ticker: "MCD", name: "McDonald's" },
        { ticker: "ACN", name: "Accenture" },
        { ticker: "ABT", name: "Abbott Labs" },
        { ticker: "CSCO", name: "Cisco Systems" },
        { ticker: "PFE", name: "Pfizer" },
        { ticker: "DHR", name: "Danaher" },
        { ticker: "INTU", name: "Intuit" },
        { ticker: "LIN", name: "Linde" },
        { ticker: "NFLX", name: "Netflix" },
        { ticker: "VZ", name: "Verizon" },
        { ticker: "INTC", name: "Intel" },
        { ticker: "AMD", name: "AMD" },
        { ticker: "CMCSA", name: "Comcast" },
        { ticker: "QCOM", name: "Qualcomm" },
        { ticker: "DIS", name: "Walt Disney" },
        { ticker: "TXN", name: "Texas Instruments" },
        { ticker: "AMGN", name: "Amgen" },
        { ticker: "NEE", name: "NextEra Energy" },
        { ticker: "PM", name: "Philip Morris" },
        { ticker: "IBM", name: "IBM" },
        { ticker: "HON", name: "Honeywell" },
        { ticker: "RTX", name: "Raytheon" },
        { ticker: "AXP", name: "American Express" },
        { ticker: "SPGI", name: "S&P Global" },
        { ticker: "CAT", name: "Caterpillar" },
        { ticker: "GS", name: "Goldman Sachs" },
        { ticker: "LOW", name: "Lowe's" },
        { ticker: "DE", name: "John Deere" },
        { ticker: "SYK", name: "Stryker" },
        { ticker: "BLK", name: "BlackRock" },
        { ticker: "MS", name: "Morgan Stanley" },
        { ticker: "BA", name: "Boeing" },
        { ticker: "ELV", name: "Elevance Health" },
        { ticker: "SBUX", name: "Starbucks" },
        { ticker: "PLD", name: "Prologis" },
        { ticker: "UPS", name: "UPS" },
        { ticker: "AMAT", name: "Applied Materials" },
        { ticker: "ISRG", name: "Intuitive Surgical" },
        { ticker: "ADP", name: "ADP" },
        { ticker: "LMT", name: "Lockheed Martin" },
        { ticker: "GILD", name: "Gilead" },
        { ticker: "PDD", name: "Pinduoduo" },
        { ticker: "MDLZ", name: "Mondelez" },
        { ticker: "T", name: "AT&T" },
        { ticker: "ADI", name: "Analog Devices" },
        { ticker: "TJX", name: "TJX Companies" },
        { ticker: "MMC", name: "Marsh & McLennan" },
        { ticker: "CVS", name: "CVS Health" },
        { ticker: "GE", name: "General Electric" },
        { ticker: "SCHW", name: "Charles Schwab" },
        { ticker: "LRCX", name: "Lam Research" },
        { ticker: "REGN", name: "Regeneron" },
        { ticker: "PGR", name: "Progressive" },
        { ticker: "ZTS", name: "Zoetis" },
        { ticker: "CI", name: "Cigna" },
        { ticker: "VRTX", name: "Vertex Pharma" },
        { ticker: "BKNG", name: "Booking Holdings" },
        { ticker: "CB", name: "Chubb" },
        { ticker: "HUM", name: "Humana" },
        { ticker: "MU", name: "Micron" },
        { ticker: "PANW", name: "Palo Alto Networks" },
        { ticker: "SNPS", name: "Synopsys" },
        { ticker: "EOG", name: "EOG Resources" },
        { ticker: "SLB", name: "Schlumberger" },
        { ticker: "BSX", name: "Boston Scientific" },
        { ticker: "ITW", name: "Illinois Tool Works" },
        { ticker: "MO", name: "Altria" },
        { ticker: "HCA", name: "HCA Healthcare" },
        { ticker: "C", name: "Citigroup" },
        { ticker: "ORCL", name: "Oracle" },
        { ticker: "CDNS", name: "Cadence" }
    ],
    India: [
        { ticker: "RELIANCE.NS", name: "Reliance Ind." },
        { ticker: "TCS.NS", name: "TCS" },
        { ticker: "HDFCBANK.NS", name: "HDFC Bank" },
        { ticker: "ICICIBANK.NS", name: "ICICI Bank" },
        { ticker: "INFY.NS", name: "Infosys" },
        { ticker: "BHARTIARTL.NS", name: "Airtel" },
        { ticker: "ITC.NS", name: "ITC Ltd." },
        { ticker: "SBIN.NS", name: "State Bank India" },
        { ticker: "LICI.NS", name: "LIC" },
        { ticker: "HINDUNILVR.NS", name: "HUL" },
        { ticker: "LT.NS", name: "Larsen & Toubro" },
        { ticker: "BAJFINANCE.NS", name: "Bajaj Finance" },
        { ticker: "HCLTECH.NS", name: "HCL Tech" },
        { ticker: "MARUTI.NS", name: "Maruti Suzuki" },
        { ticker: "SUNPHARMA.NS", name: "Sun Pharma" },
        { ticker: "ADANIENT.NS", name: "Adani Ent." },
        { ticker: "KOTAKBANK.NS", name: "Kotak Bank" },
        { ticker: "TITAN.NS", name: "Titan Company" },
        { ticker: "ONGC.NS", name: "ONGC" },
        { ticker: "TATAMOTORS.NS", name: "Tata Motors" },
        { ticker: "NTPC.NS", name: "NTPC" },
        { ticker: "AXISBANK.NS", name: "Axis Bank" },
        { ticker: "ADANIPORTS.NS", name: "Adani Ports" },
        { ticker: "COALINDIA.NS", name: "Coal India" },
        { ticker: "ADANIGREEN.NS", name: "Adani Green" },
        { ticker: "ASIANPAINT.NS", name: "Asian Paints" },
        { ticker: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
        { ticker: "JSWSTEEL.NS", name: "JSW Steel" },
        { ticker: "TATASTEEL.NS", name: "Tata Steel" },
        { ticker: "M&M.NS", name: "Mahindra & Mah." },
        { ticker: "POWERGRID.NS", name: "Power Grid" },
        { ticker: "SBILIFE.NS", name: "SBI Life" },
        { ticker: "VBL.NS", name: "Varun Beverages" },
        { ticker: "IRFC.NS", name: "IRFC" },
        { ticker: "SIEMENS.NS", name: "Siemens" },
        { ticker: "ADANIPOWER.NS", name: "Adani Power" },
        { ticker: "HAL.NS", name: "HAL" },
        { ticker: "INDIGO.NS", name: "InterGlobe" },
        { ticker: "BPCL.NS", name: "BPCL" },
        { ticker: "DLF.NS", name: "DLF" },
        { ticker: "CHOLAFIN.NS", name: "Chola Finance" },
        { ticker: "GRASIM.NS", name: "Grasim Ind." },
        { ticker: "BRITANNIA.NS", name: "Britannia" },
        { ticker: "TRENT.NS", name: "Trent" },
        { ticker: "ZOMATO.NS", name: "Zomato" },
        { ticker: "BEL.NS", name: "Bharat Elec." },
        { ticker: "HINDALCO.NS", name: "Hindalco" },
        { ticker: "NESTLEIND.NS", name: "Nestle India" },
        { ticker: "TATACONSUM.NS", name: "Tata Consumer" },
        { ticker: "GAIL.NS", name: "GAIL" },
        { ticker: "JIODFSL.NS", name: "Jio Financial" },
        { ticker: "SHREECEM.NS", name: "Shree Cement" },
        { ticker: "ADANITRANS.NS", name: "Adani Energy" },
        { ticker: "CIPLA.NS", name: "Cipla" },
        { ticker: "SBICARD.NS", name: "SBI Cards" },
        { ticker: "DRREDDY.NS", name: "Dr. Reddy's" },
        { ticker: "HDFCLIFE.NS", name: "HDFC Life" },
        { ticker: "APOLLOHOSP.NS", name: "Apollo Hosp." },
        { ticker: "TECHM.NS", name: "Tech Mahindra" },
        { ticker: "EICHERMOT.NS", name: "Eicher Motors" },
        { ticker: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
        { ticker: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
        { ticker: "DIVISLAB.NS", name: "Divi's Lab" },
        { ticker: "HINDZINC.NS", name: "Hindustan Zinc" },
        { ticker: "PIDILITIND.NS", name: "Pidilite" },
        { ticker: "TVSMOTOR.NS", name: "TVS Motor" },
        { ticker: "JINDALSTEL.NS", name: "Jindal Steel" },
        { ticker: "BANKBARODA.NS", name: "Bank of Baroda" },
        { ticker: "PNB.NS", name: "PNB" },
        { ticker: "IOC.NS", name: "IOC" },
        { ticker: "CANBK.NS", name: "Canara Bank" },
        { ticker: "UNIONBANK.NS", name: "Union Bank" },
        { ticker: "IDBI.NS", name: "IDBI Bank" },
        { ticker: "ABRETAIL.NS", name: "AB Fashion" },
        { ticker: "PAGEIND.NS", name: "Page Ind." },
        { ticker: "ACC.NS", name: "ACC" },
        { ticker: "AMBUJACEM.NS", name: "Ambuja Cement" },
        { ticker: "UBL.NS", name: "United Breweries" },
        { ticker: "MCDOWELL-N.NS", name: "United Spirits" },
        { ticker: "BERGEPAINT.NS", name: "Berger Paints" },
        { ticker: "COLPAL.NS", name: "Colgate" },
        { ticker: "SRF.NS", name: "SRF" },
        { ticker: "MUTHOOTFIN.NS", name: "Muthoot Fin." },
        { ticker: "PEL.NS", name: "Piramal Ent." },
        { ticker: "PFC.NS", name: "PFC" },
        { ticker: "RECIND.NS", name: "REC Ltd." },
        { ticker: "POLYCAB.NS", name: "Polycab" },
        { ticker: "HAVELLS.NS", name: "Havells" },
        { ticker: "KEI.NS", name: "KEI Ind." },
        { ticker: "CUMMINSIND.NS", name: "Cummins" },
        { ticker: "PERSISTENT.NS", name: "Persistent" },
        { ticker: "KPITTECH.NS", name: "KPIT Tech" },
        { ticker: "COFORGE.NS", name: "Coforge" },
        { ticker: "MPHASIS.NS", name: "Mphasis" },
        { ticker: "LTI.NS", name: "LTIMindtree" },
        { ticker: "DIXON.NS", name: "Dixon Tech" },
        { ticker: "ASTRAL.NS", name: "Astral" },
        { ticker: "SUPREMEIND.NS", name: "Supreme Ind." },
        { ticker: "BALKRISIND.NS", name: "Balkrishna Ind." },
        { ticker: "MRF.NS", name: "MRF Tyres" },
        { ticker: "APOLLOTYRE.NS", name: "Apollo Tyres" },
        { ticker: "CEATLTD.NS", name: "Ceat" },
        { ticker: "JKTYRE.NS", name: "JK Tyre" },
        { ticker: "YESBANK.NS", name: "Yes Bank" }
    ],
    Crypto: [
        { ticker: "BTC-USD", name: "Bitcoin" },
        { ticker: "ETH-USD", name: "Ethereum" },
        { ticker: "BNB-USD", name: "Binance Coin" },
        { ticker: "XRP-USD", name: "Ripple" },
        { ticker: "ADA-USD", name: "Cardano" },
        { ticker: "SOL-USD", name: "Solana" },
        { ticker: "DOGE-USD", name: "Dogecoin" },
        { ticker: "DOT-USD", name: "Polkadot" },
        { ticker: "MATIC-USD", name: "Polygon" },
        { ticker: "SHIB-USD", name: "Shiba Inu" },
        { ticker: "AVAX-USD", name: "Avalanche" },
        { ticker: "LINK-USD", name: "Chainlink" },
        { ticker: "UNI-USD", name: "Uniswap" },
        { ticker: "ATOM-USD", name: "Cosmos" },
        { ticker: "LTC-USD", name: "Litecoin" }
    ]
};
